export const FETCH_PROJECT_STRUCTURE_REQUEST = "FETCH_PROJECT_STRUCTURE_REQUEST";
export const FETCH_PROJECT_STRUCTURE_SUCCESS = "FETCH_PROJECT_STRUCTURE_SUCCESS";
export const FETCH_PROJECT_STRUCTURE_ERROR = "FETCH_PROJECT_STRUCTURE_ERROR";